// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api/proto/calc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Описание инструкции
type Instruction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Var           string                 `protobuf:"bytes,3,opt,name=var,proto3" json:"var,omitempty"`
	Left          string                 `protobuf:"bytes,4,opt,name=left,proto3" json:"left,omitempty"`
	Right         string                 `protobuf:"bytes,5,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_api_proto_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{0}
}

func (x *Instruction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Instruction) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Instruction) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *Instruction) GetLeft() string {
	if x != nil {
		return x.Left
	}
	return ""
}

func (x *Instruction) GetRight() string {
	if x != nil {
		return x.Right
	}
	return ""
}

// Ответ
type OutputItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Var           string                 `protobuf:"bytes,1,opt,name=var,proto3" json:"var,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputItem) Reset() {
	*x = OutputItem{}
	mi := &file_api_proto_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputItem) ProtoMessage() {}

func (x *OutputItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputItem.ProtoReflect.Descriptor instead.
func (*OutputItem) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{1}
}

func (x *OutputItem) GetVar() string {
	if x != nil {
		return x.Var
	}
	return ""
}

func (x *OutputItem) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OutputItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_api_proto_calc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_calc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_api_proto_calc_proto_rawDescGZIP(), []int{2}
}

func (x *Output) GetItems() []*OutputItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_proto_calc_proto protoreflect.FileDescriptor

const file_api_proto_calc_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/calc.proto\x12\x04calc\"m\n" +
	"\vInstruction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x10\n" +
	"\x03var\x18\x03 \x01(\tR\x03var\x12\x12\n" +
	"\x04left\x18\x04 \x01(\tR\x04left\x12\x14\n" +
	"\x05right\x18\x05 \x01(\tR\x05right\"4\n" +
	"\n" +
	"OutputItem\x12\x10\n" +
	"\x03var\x18\x01 \x01(\tR\x03var\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"0\n" +
	"\x06Output\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.calc.OutputItemR\x05items2<\n" +
	"\n" +
	"Calculator\x12.\n" +
	"\tCalculate\x12\x11.calc.Instruction\x1a\f.calc.Output(\x01B\x1bZ\x19goBackend/api/proto;protob\x06proto3"

var (
	file_api_proto_calc_proto_rawDescOnce sync.Once
	file_api_proto_calc_proto_rawDescData []byte
)

func file_api_proto_calc_proto_rawDescGZIP() []byte {
	file_api_proto_calc_proto_rawDescOnce.Do(func() {
		file_api_proto_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_calc_proto_rawDesc), len(file_api_proto_calc_proto_rawDesc)))
	})
	return file_api_proto_calc_proto_rawDescData
}

var file_api_proto_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_calc_proto_goTypes = []any{
	(*Instruction)(nil), // 0: calc.Instruction
	(*OutputItem)(nil),  // 1: calc.OutputItem
	(*Output)(nil),      // 2: calc.Output
}
var file_api_proto_calc_proto_depIdxs = []int32{
	1, // 0: calc.Output.items:type_name -> calc.OutputItem
	0, // 1: calc.Calculator.Calculate:input_type -> calc.Instruction
	2, // 2: calc.Calculator.Calculate:output_type -> calc.Output
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_calc_proto_init() }
func file_api_proto_calc_proto_init() {
	if File_api_proto_calc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_calc_proto_rawDesc), len(file_api_proto_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_calc_proto_goTypes,
		DependencyIndexes: file_api_proto_calc_proto_depIdxs,
		MessageInfos:      file_api_proto_calc_proto_msgTypes,
	}.Build()
	File_api_proto_calc_proto = out.File
	file_api_proto_calc_proto_goTypes = nil
	file_api_proto_calc_proto_depIdxs = nil
}
