// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "description": "API для вычислений инструкций",
    "title": "Calculator API",
    "version": "1.0"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "paths": {
    "/calculate": {
      "post": {
        "description": "Обрабатывает инструкции типа calc и print",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Вычислить список инструкций",
        "parameters": [
          {
            "description": "Список инструкций",
            "name": "instructions",
            "in": "body",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/model.Instruction"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/model.Output"
            }
          },
          "400": {
            "description": "Ошибка ввода",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "model.Instruction": {
      "type": "object",
      "properties": {
        "left": {},
        "op": {
          "type": "string"
        },
        "right": {},
        "type": {
          "type": "string"
        },
        "var": {
          "type": "string"
        }
      }
    },
    "model.Output": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/model.OutputItem"
          }
        }
      }
    },
    "model.OutputItem": {
      "type": "object",
      "properties": {
        "value": {
          "type": "integer",
          "format": "int64"
        },
        "var": {
          "type": "string"
        }
      }
    }
  }
}`

var s = swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Calculator API",
	Description:      "API для вычислений инструкций",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register("swagger", &s)
}
